import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { api, json } from "../api/client";
import type { ApprovalPolicy, ProjectAccess, ProjectMembership, ProjectRole } from "../types";

type AvailableUser = { id: string; display_name: string; email: string; provider: string; provider_username: string };
type GovernanceProfile = { id: string; key: string; name: string; enabled: boolean; applies_to_tags: string[]; required_policy_keys: string[]; prohibit_self_approval: boolean; min_total_approvals: number };
type AuditEvent = { id: number; action: string; target_type: string; target_id: string | null; actor_snapshot: { display_name?: string; email?: string }; created_at: string };

export function ProjectAdminPage() {
  const { projectId = "" } = useParams();
  const client = useQueryClient();
  const [roleOpen, setRoleOpen] = useState(false);
  const [memberOpen, setMemberOpen] = useState(false);
  const [policyOpen, setPolicyOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const access = useQuery({ queryKey: ["project-access", projectId], queryFn: () => api<ProjectAccess>(`/projects/${projectId}/access`) });
  const roles = useQuery({ queryKey: ["project-roles", projectId], enabled: access.data?.permissions.includes("role.manage"), queryFn: () => api<ProjectRole[]>(`/projects/${projectId}/roles`) });
  const memberships = useQuery({ queryKey: ["project-memberships", projectId], enabled: access.data?.permissions.includes("membership.manage"), queryFn: () => api<ProjectMembership[]>(`/projects/${projectId}/memberships`) });
  const users = useQuery({ queryKey: ["project-users", projectId], enabled: access.data?.permissions.includes("membership.manage"), queryFn: () => api<AvailableUser[]>(`/projects/${projectId}/available-users`) });
  const policies = useQuery({ queryKey: ["approval-policies", projectId], queryFn: () => api<ApprovalPolicy[]>(`/projects/${projectId}/approval-policies`) });
  const profiles = useQuery({ queryKey: ["governance-profiles", projectId], enabled: access.data?.permissions.includes("policy.manage"), queryFn: () => api<GovernanceProfile[]>(`/projects/${projectId}/governance-profiles`) });
  const audit = useQuery({ queryKey: ["authorization-audit", projectId], enabled: access.data?.permissions.includes("audit.view"), queryFn: () => api<AuditEvent[]>(`/projects/${projectId}/authorization-audit`) });
  const permissions = useQuery({ queryKey: ["permission-catalog"], enabled: access.data?.is_system_admin, queryFn: () => api<string[]>("/admin/permissions") });
  const invalidate = () => { void client.invalidateQueries({ queryKey: ["project-roles", projectId] }); void client.invalidateQueries({ queryKey: ["project-memberships", projectId] }); void client.invalidateQueries({ queryKey: ["approval-policies", projectId] }); void client.invalidateQueries({ queryKey: ["governance-profiles", projectId] }); void client.invalidateQueries({ queryKey: ["authorization-audit", projectId] }); };
  const save = useMutation({ mutationFn: ({ path, payload, method = "PUT" }: { path: string; payload: unknown; method?: string }) => api(path, json(method, payload)), onSuccess: () => { invalidate(); setRoleOpen(false); setMemberOpen(false); setPolicyOpen(false); setProfileOpen(false); } });
  function roleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const key = String(data.get("key")); save.mutate({ path: `/projects/${projectId}/roles`, method: "POST", payload: { key, name: data.get("name"), description: data.get("description"), permissions: data.getAll("permissions") } }); }
  function memberSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const userId = String(data.get("user_id")); save.mutate({ path: `/projects/${projectId}/memberships/${userId}`, payload: { user_id: userId, role_keys: data.getAll("role_keys"), is_active: true } }); }
  function policySubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const key = String(data.get("key")); try { const requirements = JSON.parse(String(data.get("requirements"))) as unknown; save.mutate({ path: `/projects/${projectId}/approval-policies/${key}`, payload: { key, name: data.get("name"), description: data.get("description"), enabled: true, initiator_may_approve: data.get("initiator") === "on", distinct_approvers_across_requirements: data.get("distinct") === "on", eligible_approvers_may_give_feedback: true, requirements } }); } catch { /* keep dialog open */ } }
  function profileSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const key = String(data.get("key")); save.mutate({ path: `/projects/${projectId}/governance-profiles/${key}`, payload: { key, name: data.get("name"), enabled: true, applies_to_tags: String(data.get("tags") ?? "").split(",").map((value) => value.trim()).filter(Boolean), required_policy_keys: data.getAll("policy_keys"), prohibit_self_approval: data.get("prohibit") === "on", min_total_approvals: Number(data.get("minimum") ?? 1) } }); }
  return <section><header className="page-header"><div><Link className="eyebrow" to="/projects">← Projects</Link><h1>Access & governance</h1><p>Manage project-scoped roles, memberships, approval policies, and conformance profiles.</p></div></header>
    <div className="admin-grid">
      {access.data?.permissions.includes("membership.manage") && <div className="panel admin-panel"><div className="panel-title"><h2>Members</h2><button onClick={() => setMemberOpen(true)}>Add or update</button></div><table><tbody>{memberships.data?.map((member) => <tr key={member.id}><td><strong>{member.display_name}</strong><small className="block muted">{member.email}</small></td><td>{member.role_keys.join(", ") || "No roles"}</td><td>{member.is_active ? "Active" : "Disabled"}</td><td><button className="ghost" disabled={save.isPending} onClick={() => save.mutate({ path: `/projects/${projectId}/memberships/${member.user_id}`, payload: { user_id: member.user_id, role_keys: member.role_keys, is_active: !member.is_active } })}>{member.is_active ? "Disable" : "Enable"}</button></td></tr>)}</tbody></table></div>}
      {access.data?.permissions.includes("role.manage") && <div className="panel admin-panel"><div className="panel-title"><h2>Roles</h2><button onClick={() => setRoleOpen(true)}>Custom role</button></div><table><tbody>{roles.data?.map((role) => <tr key={role.id}><td><strong>{role.name}</strong><small className="block mono">{role.key}</small></td><td>{role.permissions.length} permissions</td><td>{role.is_builtin ? "Built in" : "Custom"}</td></tr>)}</tbody></table></div>}
      <div className="panel admin-panel"><div className="panel-title"><h2>Approval policies</h2>{access.data?.permissions.includes("policy.manage") && <button onClick={() => setPolicyOpen(true)}>New policy</button>}</div>{policies.data?.map((policy) => <article className="admin-list-item" key={policy.id}><strong>{policy.name}</strong><code>{policy.key}</code><p>{policy.requirements.map((requirement) => `${requirement.name}: ${requirement.quorum}${requirement.include_triggering_user ? " (workflow triggerer)" : ""}`).join(" · ")}</p><small>{policy.initiator_may_approve ? "Initiator may approve" : "Independent approval"} · {policy.distinct_approvers_across_requirements ? "Distinct approvers" : "Overlapping approvers allowed"}</small></article>)}</div>
      {access.data?.permissions.includes("policy.manage") && <div className="panel admin-panel"><div className="panel-title"><h2>Governance profiles</h2><button onClick={() => setProfileOpen(true)}>New profile</button></div>{profiles.data?.map((profile) => <article className="admin-list-item" key={profile.id}><strong>{profile.name}</strong><code>{profile.key}</code><p>Requires {profile.required_policy_keys.join(", ") || "no named policy"} · minimum {profile.min_total_approvals} approvals</p></article>)}</div>}
      {access.data?.permissions.includes("audit.view") && <div className="panel admin-panel admin-panel-wide"><div className="panel-title"><h2>Authorization audit</h2><span className="muted">Latest {Math.min(audit.data?.length ?? 0, 20)} events</span></div><table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Target</th></tr></thead><tbody>{audit.data?.slice(0, 20).map((event) => <tr key={event.id}><td>{new Date(event.created_at).toLocaleString()}</td><td>{event.actor_snapshot.display_name ?? event.actor_snapshot.email ?? "System"}</td><td><code>{event.action}</code></td><td>{event.target_type}{event.target_id ? ` · ${event.target_id}` : ""}</td></tr>)}</tbody></table></div>}
    </div>
    {memberOpen && <div className="modal-backdrop"><form className="modal" onSubmit={memberSubmit}><h2>Add or update member</h2><label>User<select name="user_id" required>{users.data?.map((user) => <option key={user.id} value={user.id}>{user.display_name} · {user.email}</option>)}</select></label><label>Roles<select name="role_keys" multiple size={Math.min(8, roles.data?.length ?? 3)}>{roles.data?.map((role) => <option key={role.id} value={role.key}>{role.name}</option>)}</select></label><footer><button type="button" className="secondary" onClick={() => setMemberOpen(false)}>Cancel</button><button>Save membership</button></footer></form></div>}
    {roleOpen && <div className="modal-backdrop"><form className="modal" onSubmit={roleSubmit}><h2>Create custom role</h2><label>Key<input name="key" required pattern="[a-z0-9][a-z0-9._-]*" /></label><label>Name<input name="name" required /></label><label>Description<textarea name="description" /></label><label>Permissions<select name="permissions" multiple size={10}>{(permissions.data ?? access.data?.permissions ?? []).map((permission) => <option key={permission}>{permission}</option>)}</select></label><footer><button type="button" className="secondary" onClick={() => setRoleOpen(false)}>Cancel</button><button>Create role</button></footer></form></div>}
    {policyOpen && <div className="modal-backdrop"><form className="modal" onSubmit={policySubmit}><h2>Create approval policy</h2><label>Key<input name="key" required /></label><label>Name<input name="name" required /></label><label>Description<textarea name="description" /></label><label className="check-field"><input type="checkbox" name="initiator" /> Initiator may approve</label><label className="check-field"><input type="checkbox" name="distinct" defaultChecked /> Require distinct approvers across requirements</label><label>Requirements JSON<textarea name="requirements" className="code-editor" defaultValue={'[\n  {"key":"review","name":"Review","quorum":1,"role_keys":["approver"],"user_ids":[]}\n]'} /></label><footer><button type="button" className="secondary" onClick={() => setPolicyOpen(false)}>Cancel</button><button>Save policy</button></footer></form></div>}
    {profileOpen && <div className="modal-backdrop"><form className="modal" onSubmit={profileSubmit}><h2>Create governance profile</h2><label>Key<input name="key" required /></label><label>Name<input name="name" required /></label><label>Applies to workflow tags<input name="tags" placeholder="production, regulated" /></label><label>Required policies<select name="policy_keys" multiple>{policies.data?.map((policy) => <option key={policy.id} value={policy.key}>{policy.name}</option>)}</select></label><label>Minimum total approvals<input name="minimum" type="number" min="1" defaultValue="1" /></label><label className="check-field"><input type="checkbox" name="prohibit" /> Prohibit initiator approval</label><footer><button type="button" className="secondary" onClick={() => setProfileOpen(false)}>Cancel</button><button>Save profile</button></footer></form></div>}
    {save.error && <p className="error">{save.error.message}</p>}
  </section>;
}
